### ISSUE TITLE
Register Doctor Activity Button 

### ISSUE THREAD

**Issue by Dylan-Fasser** [freezy04/Runtime-Terror#12]
Hey Everyone 

The Register button for the Register Doctor Activity does not seem to work, the button doesn't take the user anywhere or verify whether the details we captured or not, when attempting to log in, the user details are also not valid meaning the doctor was not registered.

Tha

**Comment by GabrielTidy** [comment]
Fixed. One of the input fields was accidentally removed and caused issues with the validation code.
