### ISSUE TITLE
No way to select Time for new Appointment

### ISSUE THREAD

**Issue by GabrielTidy** [freezy04/Runtime-Terror#17]
I'm not sure if I'm just missing something but when I try to book an appointment as a patient, the selection tool for the time doesn't let me save my selection. This means the "Time" field remains null no matter what I do, causing a crash once I book.

**Comment by freezy04** [comment]
I'll look into it and do the validation also

**Comment by GabrielTidy** [comment]
Reworked the TimePickerDialog as the confirm buttons were not visible using an emulator
