### ISSUE TITLE
Login Button 

### ISSUE THREAD

**Issue by 1866305** [freezy04/Runtime-Terror#2]
I have noticed that the login button doesn't work on our main page, it suppose to take us to its Login page for the users who are already registered to just login, can anyone from the Back End Code fix that .Thank you

**Comment by 1866305** [comment]
![MobiDoc](https://user-images.githubusercontent.com/69643483/113820923-aa5e2400-977b-11eb-8df4-582456a8da57.jpeg)

**Comment by Dylan-Fasser** [comment]
Good Day , Thank you for pointing this bug out , I have made the necessary changes to fix this and it should be working effective next commit , please find the attached screenshots for reference :
![screenshot_post_home_click](https://user-images.githubusercontent.com/69579210/113822153-5eac7a00-977d-11eb-82f7-e5c12116b055.PNG)
![screenshot_login_home](https://user-images.githubusercontent.com/69579210/113822166-62d89780-977d-11eb-8ef0-1c76f920ee9b.PNG)
