### ISSUE TITLE
Nav Bar Link Broken

### ISSUE THREAD

**Issue by Dylan-Fasser** [freezy04/Runtime-Terror#31]
On the home page for a patient , the nav bar is unlinked and sends the user to a 404

**Comment by kgosi-gabaocwe** [comment]
I will check it out

**Comment by kgosi-gabaocwe** [comment]
Yo Dylan, what do you mean, it's been working fine for me, I was never sent to a 404

**Comment by Dylan-Fasser** [comment]
Managed to fix the dead links
