### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by freezy04** [freezy04/Runtime-Terror#4]
Can't access login page when clicking the login button.

**Comment by Dylan-Fasser** [comment]
I managed to fix the error, the Successful Login redirected back to the Sign In/ Sign Up Page , I've made the necessary changed to combat this issue , the Successful Login page , redirects to a Dashboard page .

Thank you 

![image](https://user-images.githubusercontent.com/69579210/113927808-3e68d380-97ee-11eb-9f0c-a045f75c1d12.png)
